import Head from "next/head";
import NewsletterForm from "~/components/NewsletterForm";
import Socials from "~/components/Socials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Salmandotweb</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#03040B] p-10">
        <div className="space-y-1">
          <h2 className="text-stroke animate-title z-10 cursor-default whitespace-nowrap bg-white bg-clip-text text-center text-3xl font-bold text-transparent duration-1000 sm:text-5xl md:text-6xl">
            Join the waitlist for my
          </h2>
          <h1 className="animate-fade-in-3 z-10 cursor-default whitespace-nowrap bg-white bg-gradient-to-r from-purple-300 to-purple-800 bg-clip-text text-center text-4xl font-bold text-transparent duration-1000 sm:text-6xl md:text-7xl">
            Newsletter
          </h1>
        </div>
        <NewsletterForm />
        <Socials />
      </main>
    </>
  );
}
